project_id = "rjbdcucejlsegbgqmoao"

[functions.process-daily-returns]
verify_jwt = false

[functions.send-signup-email]
verify_jwt = false

[functions.send-reset-email]
verify_jwt = false

[functions.send-2fa-code]
verify_jwt = false

[functions.verify-2fa-code]
verify_jwt = false

[functions.delete-user]
verify_jwt = false
